# This compose file combines the docker-mailserver and its GUI.
# It builds the GUI from the local source and pulls the mailserver image.
# IMPORTANT: Before deploying, change the placeholder values below.

services:
  # --------------------------------------------------
  # The main Docker Mailserver service
  # --------------------------------------------------
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # IMPORTANT: Use your actual mail domain here.
    # The hostname should be the mail subdomain (e.g., mail.yourdomain.com).
    hostname: mail.yourdomain.com
    environment:
      # --- Hostname & Certificate Fix ---
      # OVERRIDE_HOSTNAME explicitly tells the startup script what domain to use
      # for certificate generation, fixing the self-signed cert error.
      - OVERRIDE_HOSTNAME=oonto.dk
      # POSTMASTER_ADDRESS is required for a valid Dovecot configuration.
      - POSTMASTER_ADDRESS=admin@oonto.dk

      # --- Security & SSL ---
      # For production, change SSL_TYPE to 'letsencrypt' and set DMS_LETSENCRYPT_EMAIL.
      - SSL_TYPE=self-signed
      # - DMS_LETSENCRYPT_EMAIL=your-admin-email@yourdomain.com
      - SPOOF_PROTECTION=1
      - ENABLE_FAIL2BAN=true

    ports:
      - "25:25"    # SMTP
      - "143:143"  # IMAP
      - "465:465"  # SMTPS
      - "587:587"  # MSA
      - "993:993"  # IMAPS
    volumes:
      # --- Persistent Data Mapping ---
      # Maps mailserver data to your Unraid cache drive as requested.
      # NOTE: Ensure the host paths have correct write permissions (e.g., chmod -R 777)
      - /mnt/cache/ONTO/MAIL/maildata/:/var/mail/
      - /mnt/cache/ONTO/MAIL/mailstate/:/var/mail-state/
      - /mnt/cache/ONTO/MAIL/logs/:/var/log/mail/
      - /mnt/cache/ONTO/MAIL/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro # Sync container time with host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN # Required for Fail2Ban

  # --------------------------------------------------
  # The docker-mailserver-GUI service
  # --------------------------------------------------
  mailserver-gui:
    # This tells Docker to build the image from the Dockerfile
    # in the current directory (your forked repo).
    build: .
    container_name: mailserver-gui
    ports:
      - "801:80"
    environment:
      # This tells the GUI which container to manage.
      # It MUST match the container_name of the mailserver service above.
      - DOCKER_CONTAINER=mailserver
    volumes:
      # Mounts the Docker socket so the GUI can communicate with the Docker API.
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    # This ensures the mailserver is started before the GUI attempts to connect.
    depends_on:
      - mailserver
