version: '3.8'

services:
  # Combined frontend and backend service
  mailserver-gui:
    build: .
    container_name: mailserver-gui
    ports:
      - "801:80"
    environment:
      - PORT=3001
      - NODE_ENV=production
      # The name of the docker-mailserver container
      - DOCKER_CONTAINER=mailserver
    volumes:
      # Mount the docker socket to allow container communication with Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

# No networks or volumes needed as we're using Docker API via the socket
